CREATE TABLE CLINICA (
  ID_CLINICA NUMBER(6) PRIMARY KEY,
  NOME_CLINICA VARCHAR2(50) NOT NULL,
  ENDERECO_CLINICA VARCHAR2(100) NOT NULL,
  CNPJ VARCHAR2(15),
  TELEFONE_CLINICA VARCHAR2(15)
);

CREATE TABLE CONSULTAS (
  ID_CONSULTA NUMBER(6) PRIMARY KEY,
  NOME_CLINICA VARCHAR2(50) NOT NULL,
  ENDERECO_CLINICA VARCHAR2(100) NOT NULL,
  TELEFONE_CLINICA VARCHAR2(15),
  ID_PACIENTE NUMBER(6),
  TIPO_CONSULTA VARCHAR2(15),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);

CREATE TABLE SECRETARIA (
  ID_SECRETARIA NUMBER(6) PRIMARY KEY,
  NOME_SECRETARIA VARCHAR2(50) NOT NULL,
  ENDERECO_SECRETARIA VARCHAR2(100) NOT NULL,
  TELEFONE_SECRETARIA VARCHAR2(15),
  ID_CLINICA NUMBER(6),
  FOREIGN KEY (ID_CLINICA) REFERENCES CLINICA(ID_CLINICA)
);

CREATE TABLE EXAMES (
  ID_EXAME NUMBER(6) PRIMARY KEY,
  TIPO_EXAME VARCHAR2(20) NOT NULL,
  DATA_EXAME VARCHAR2(8),
  ID_PACIENTE NUMBER(6),
  ID_MEDICO NUMBER(6),
  ID_SECRETARIA NUMBER(6),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE),
  FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
  FOREIGN KEY (ID_SECRETARIA) REFERENCES SECRETARIA(ID_SECRETARIA)
);

CREATE TABLE HISTORICOS (
  ID_HISTORICO NUMBER(6) PRIMARY KEY,
  ID_EXAME NUMBER(6),
  ID_MEDICO NUMBER(6),
  TIPO_EXAME VARCHAR2(20) NOT NULL,
  TIPO_CONSULTA VARCHAR2(20) NOT NULL,
  ID_SECRETARIA NUMBER(6),
  FOREIGN KEY (ID_EXAME) REFERENCES EXAMES(ID_EXAME),
  FOREIGN KEY (ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
  FOREIGN KEY (ID_SECRETARIA) REFERENCES SECRETARIA(ID_SECRETARIA)
);

CREATE TABLE MEDICO (
  ID_MEDICO NUMBER(6) PRIMARY KEY,
  NOME_MEDICO VARCHAR2(50) NOT NULL,
  ENDERECO_MEDICO VARCHAR2(100) NOT NULL,
  CRM VARCHAR2(15),
  TELEFONE_MEDICO VARCHAR2(15)
);

CREATE TABLE PACIENTE (
  ID_PACIENTE NUMBER(6) PRIMARY KEY,
  NOME_PACIENTE VARCHAR2(50) NOT NULL,
  ENDERECO_PACIENTE VARCHAR2(100) NOT NULL,
  CPF VARCHAR2(15),
  TELEFONE_PACIENTE VARCHAR2(15)
);

CREATE TABLE PLANO_DE_SAUDE (
  ID_PLANO NUMBER(6) PRIMARY KEY,
  ID_PACIENTE NUMBER(6),
  NUMERO_CARTEIRA NUMBER(20),
  VALIDADE NUMBER(8),
  ABRANGENCIA VARCHAR2(15),
  FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);
